### ISSUE TITLE
GeoJson Export

### ISSUE THREAD

**Issue by smkraus** [technologiestiftung/berlin_sidewalk_widths#9]
Hey there, is there any way you could export the final data as GeoJson. I'm working on a map to identify key areas for traffic-calming and opening streets for Changing Cities. Thank you so much!

**Comment by fabianmoronzirfas** [comment]
@smkraus Isn't that what you are looking for? https://github.com/technologiestiftung/berlin_sidewalk_widths/tree/7467a409b499afc0036e86bbe1c47cf280594edc/public/data

**Comment by smkraus** [comment]
Oh, right, thanks a lot. When reading the documentation, I had the impression, that there are only test exports.

**Comment by Lisa-Stubert** [comment]
@smkraus Sorry, the readme is actually misleading, I'll edit it. Nevertheless I just uploaded the dataset all.geojson again, it is now a more recent version, which corresponds to the dataset shown in the web map. It is best to use this updated version. I'd be curious to see the results of your analysis.
